version: '3.9'

networks:
  travel_net:
    driver: bridge

services:
  user-service:
    build: ./user_service
    container_name: user_service
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.shared
      - ./user_service/.env
    volumes:
      - ./user_service:/app
    depends_on:
      - db
    networks:
      - travel_net

  db:
    image: postgres:15
    restart: always
    env_file:
      - ./user_service/.env
    volumes:
      - user_postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - travel_net

  package-service:
    build: ./package_service
    container_name: package_service
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.shared
      - ./package_service/.env
    volumes:
      - ./package_service:/app
    depends_on:
      - package_db
    networks:
      - travel_net

  package_db:
    image: postgres:15
    restart: always
    env_file:
      - ./package_service/.env
    volumes:
      - package_postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - travel_net

  booking-service:
    build: ./booking_service
    container_name: booking_service
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.shared
      - ./booking_service/.env
    volumes:
      - ./booking_service:/app
    depends_on:
      - booking_db
    networks:
      - travel_net

  booking_db:
    image: postgres:15
    restart: always
    env_file:
      - ./booking_service/.env
    volumes:
      - booking_postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - travel_net

  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - package-service
      - booking-service
    networks:
      - travel_net

volumes:
  user_postgres_data:
  package_postgres_data:
  booking_postgres_data:

